### ISSUE TITLE
Names of great people don't included in credits

### ISSUE THREAD

**Issue by ghost** [SDLash3D/cs16-client#90]
Client uses parts of third party code. Developers must be mentioned in credits.

**Comment by a1batross** [comment]
Look at the 46 line of mainui/menu_credits.cpp. These strings is showed in
Credits page in cs16client custom menu. It's outdated, but anyway...

I didn't forgot about these great people: @Nagist, @s1lentq, SoHL
developers, Uncle Mike, @jeefo.

Because this still in early development, I just don't waste time on
READMEs, documetation and wiki. Main goal now is to fix all bugs.

Until cs16client not released, this repo is only for beta testers. I
already realized, that posting source code before release was been a
mistake.

**Comment by a1batross** [comment]
I rewrited credits, so this is issue can be closed.
